### PR TITLE
Port to Meson

### PR DESCRIPTION
**Pull request by ernestask**
The Java bits are rather ugly, but it’s not too convoluted.

### CODE REVIEW

**Comment by mkutlak** [comment]
Is this review ready?

**Comment by ernestask** [comment]
Yes, should be. Seems like the Rawhide build failed, but it’s not an actual build failure.

**Comment by ernestask** [comment]
Added an EPEL 8 target to the Packit config.

**Comment by ernestask** [comment]
Rebased atop master.

**Comment by mkutlak** [comment]
<p align=center>
L G T M
</p>

**Pull request merged**
